version: "3"
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - rails_api_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      host: localhost
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "3001:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "3002:8080"
    volumes:
      - ./docs/api/schema.yml:/schema.yml
    environment:
      SWAGGER_JSON: /schema.yml
  swagger-api:
    image: stoplight/prism:3
    ports:
      - "4010:4010"
    command: mock -h 0.0.0.0 /schema.yml
    volumes:
      - ./docs/api/schema.yml:/schema.yml
volumes:
  rails_api_data:
    driver: local
